routingAdmin:
    resource: "@EcommerceBundle/Resources/config/routing/routingAdmin.yml"
    prefix: /admin

routingCommandesAdmin:
    resource: "@EcommerceBundle/Resources/config/routing/routingCommandesAdmin.yml"
    prefix: /admin/commandes

routingCategoriesAdmin:
    resource: "@EcommerceBundle/Resources/config/routing/routingCategoriesAdmin.yml"
    prefix:   /admin/categories

routingProduitsAdmin:
    resource: "@EcommerceBundle/Resources/config/routing/routingProduitsAdmin.yml"
    prefix:   /admin/produits

routingPanier:
    resource: "@EcommerceBundle/Resources/config/routing/routingPanier.yml"
    prefix: /panier

routingProduits:
    resource: "@EcommerceBundle/Resources/config/routing/routingProduits.yml"
    prefix: /

routingCommandes:
    resource: "@EcommerceBundle/Resources/config/routing/routingCommandes.yml"
    prefix: /

